name: Build and Push Image

on:
  push:
    branches:
      - docker

env:
  PROJECT_ID: secure-racer-350406
  GAR_LOCATION: asia-northeast1
  IMAGE_NAME: nodejs-server
  REPOSITORY: nodejs-project
  REGION: asia-northeast1

jobs:
  build-and-publish:
    name: Build and Push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: set TAG
        run: |
          echo "TAG=$(echo $GITHUB_REF | awk -F/ '{print $NF}')" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" -f Dockerfile.dev ./

      - name: Push
        run: |
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

#       - name: Deploy to Cloud Run
#         id: deploy
#         uses: google-github-actions/deploy-cloudrun@v0
#         with:
#           service: ${{ env.IMAGE_NAME }}
#           region: ${{ env.REGION }}
#           image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

#       - name: Show Output
#         run: echo ${{ steps.deploy.outputs.url }}
